[package]
name = "jwts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwt = "0.16.0"
hmac = "0.12.1"
serde = "1.0"
sha2 = "0.10.2"
serde_json = "1.0.82"
